# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0002_articles_article_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_content',
            field=models.TextField(null=True),
        ),
    ]
