# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0003_articles_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('Last_name', models.CharField(max_length=250)),
                ('text_content', models.TextField(null=True)),
                ('email_address', models.EmailField(max_length=250)),
            ],
        ),
    ]
