# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0005_contact_us_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=250)),
                ('Last_name', models.CharField(max_length=250)),
                ('text_content', models.TextField(null=True)),
                ('email_address', models.EmailField(max_length=250)),
                ('phone_number', models.IntegerField(null=True)),
                ('Country', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact_Us',
        ),
    ]
