# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0006_auto_20170330_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_hit',
            field=models.CharField(default='hit', max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Country',
            field=models.CharField(max_length=2500),
        ),
    ]
