# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0009_auto_20170405_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='link_author',
            field=models.CharField(default='facebook.com', max_length=250),
        ),
    ]
