# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0010_auto_20170405_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='link_author',
        ),
    ]
