# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-09 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0012_remove_articles_article_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author_pic',
        ),
        migrations.AddField(
            model_name='articles',
            name='article_album',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
