# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0014_articles_author_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_album',
            field=models.FileField(upload_to=''),
        ),
    ]
